---
- name: Converge
  hosts: nexus
  collections:
    - cloudkrafter.nexus

  roles:
    - role: cloudkrafter.nexus.nexus_oss
  vars_files:
    - ssl-{{ ansible_os_family }}.yml
    - nexus_common_test_vars.yml
    - nexus_ldap_test_vars.yml
    - nexus_postgres_test_vars.yml

  environment:
    http_proxy: "{{ lookup('env', 'http_proxy') }}"
    https_proxy: "{{ lookup('env', 'https_proxy') }}"
    no_proxy: "{{ lookup('env', 'no_proxy') }}"
