---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker
  safe_files:
    - nexus-downloads

platforms:
  - name: cluster-1
    hostname: cluster-1
    image: brianveltman/molecule_openjdk17:rockylinux9
    pull: true
    pre_build_image: true
    privileged: true
    published_ports:
      - 9091:443
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .nexus-downloads:/nexus-downloads
    cgroupns_mode: host
    groups:
      - nexus
    networks: &nexus_networks
      - name: nexus-default
  - name: cluster-2
    hostname: cluster-2
    image: brianveltman/molecule_openjdk17:rockylinux9
    pull: true
    pre_build_image: true
    privileged: true
    published_ports:
      - 9092:443
    override_command: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - .nexus-downloads:/nexus-downloads
    cgroupns_mode: host
    groups:
      - nexus
    networks: *nexus_networks

  - name: slapd-server-mock
    hostname: slapd-server-mock
    image: thoteam/slapd-server-mock:latest
    override_command: false
    pull: true
    pre_build_image: true
    env:
      LDAP_DOMAIN: slapd-server-mock
    groups:
      - mockldap
    networks: *nexus_networks

  # container instance to run postgresql database
  - name: postgresql-server
    hostname: postgresql-server
    image: postgres:14-bullseye
    override_command: false
    pull: true
    pre_build_image: true
    published_ports:
      - 5432:5432
    env:
      POSTGRES_DB: nexus
      POSTGRES_USER: nexus
      POSTGRES_PASSWORD: nexus
    groups:
      - postgresql
    networks: *nexus_networks

provisioner:
  name: ansible

scenario:
  check_sequence:
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - create
    - converge
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - check
    - verify
    - destroy

verifier:
  name: testinfra

role_name_check: 2
